package org.pdfgal.pdfgalweb.services.impl;

import java.io.IOException;
import java.util.List;

import javax.servlet.http.HttpServletResponse;

import org.apache.commons.collections.CollectionUtils;
import org.apache.commons.lang3.StringUtils;
import org.apache.pdfbox.exceptions.COSVisitorException;
import org.pdfgal.pdfgal.model.PDFGalBookmark;
import org.pdfgal.pdfgal.pdfgal.PDFGal;
import org.pdfgal.pdfgalweb.forms.DownloadForm;
import org.pdfgal.pdfgalweb.services.BookmarkService;
import org.pdfgal.pdfgalweb.utils.FileUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.multipart.MultipartFile;

public class BookmarkServiceImpl implements BookmarkService {

	@Autowired
	private FileUtils fileUtils;

	@Autowired
	private PDFGal pdfGal;

	@Override
	public DownloadForm addBookmarks(final MultipartFile file, final String title,
			final List<PDFGalBookmark> pdfGalBookmarksList, final HttpServletResponse response)
			throws Exception {

		DownloadForm result = new DownloadForm();

		if (file != null && StringUtils.isNotBlank(title)
				&& CollectionUtils.isNotEmpty(pdfGalBookmarksList) && response != null) {

			final String originalName = file.getOriginalFilename();
			final String inputUri = this.fileUtils.saveFile(file);
			final String outputUri = this.fileUtils.getAutogeneratedName(originalName);

			// File is bookmarked
			try {
				this.pdfGal.addBookmarks(inputUri, outputUri, title, pdfGalBookmarksList);
			} catch (COSVisitorException | IOException e) {
				// Temporal files are deleted from system
				this.fileUtils.delete(inputUri);
				this.fileUtils.delete(outputUri);
				throw e;
			}

			// Temporal files are deleted from system
			this.fileUtils.delete(inputUri);

			result = new DownloadForm(outputUri, originalName);
		}

		return result;
	}

}
