package org.pdfgal.pdfgalweb.services.impl;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletResponse;

import org.apache.commons.collections.CollectionUtils;
import org.apache.commons.lang3.StringUtils;
import org.apache.pdfbox.exceptions.COSVisitorException;
import org.pdfgal.pdfgal.pdfgal.PDFGal;
import org.pdfgal.pdfgalweb.services.MergeService;
import org.pdfgal.pdfgalweb.utils.FileUtils;
import org.pdfgal.pdfgalweb.utils.ZipUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

@Service
public class MergeServiceImpl implements MergeService {

	@Autowired
	private FileUtils fileUtils;

	@Autowired
	private PDFGal pdfGal;

	@Autowired
	private ZipUtils zipUtils;

	@Override
	public void merge(final List<MultipartFile> files, final String fileName,
			final HttpServletResponse response) {

		if (CollectionUtils.isNotEmpty(files)
				&& StringUtils.isNotBlank(fileName)) {

			List<String> inputUris = new ArrayList<String>();
			final String outputUri = this.fileUtils
					.getAutogeneratedName(fileName);

			if (files.size() == 1) {
				// It's a ZIP file
				try {
					inputUris = this.zipUtils.saveFilesFromZip(files.get(0)
							.getInputStream());
				} catch (final IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}

			} else {
				// They are PDF files
				inputUris = this.fileUtils.saveFile(files);
			}

			try {
				// Merge documents
				this.pdfGal.merge(inputUris, outputUri);

				// File is prepared for download
				this.fileUtils.prepareFileDownload(response, outputUri,
						fileName);

			} catch (COSVisitorException | IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} finally {
				this.fileUtils.delete(inputUris);
				this.fileUtils.delete(outputUri);
			}

		} else {
			// TODO
		}
	}

}
