package org.pdfgal.pdfgalweb.services.impl;

import java.io.IOException;

import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang3.StringUtils;
import org.apache.pdfbox.exceptions.COSVisitorException;
import org.apache.pdfbox.pdmodel.encryption.BadSecurityHandlerException;
import org.pdfgal.pdfgal.pdfgal.PDFGal;
import org.pdfgal.pdfgalweb.services.ProtectService;
import org.pdfgal.pdfgalweb.utils.FileUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

@Service
public class ProtectServiceImpl implements ProtectService {

	@Autowired
	private FileUtils fileUtils;

	@Autowired
	private PDFGal pdfGal;

	@Override
	public void protect(final MultipartFile file, final String password,
			final String repeatedPassword, final HttpServletResponse response)
			throws COSVisitorException, IOException,
			BadSecurityHandlerException {

		if (!file.isEmpty() && StringUtils.isNotBlank(password)
				&& StringUtils.isNotBlank(repeatedPassword)
				&& password.equals(repeatedPassword)) {

			final String originalName = file.getOriginalFilename();
			final String inputUri = this.fileUtils.saveFile(file);
			final String outputUri = this.fileUtils
					.getAutogeneratedName(originalName);

			// File is protected
			this.pdfGal.protect(inputUri, outputUri, password);

			// The protected file is prepared for download
			this.fileUtils.prepareFileDownload(response, outputUri,
					originalName);

			// Temporal files are deleted from system
			this.fileUtils.delete(inputUri);
			this.fileUtils.delete(outputUri);
		}

	}

}
